# Generated by Django 5.2.9 on 2025-12-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
