# Generated by Django 5.2.9 on 2025-12-06 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_otp_created_at_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
